services:
  - type: web
    name: nomad-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: starter
    pythonVersion: "3.12"
    buildFilter:
      paths:
        - requirements.txt
        - pyproject.toml
        - app/**
        - run.py
        - config.py 